version: '3.8'
services:
  redis:
    image: redis:alpine3.20
    container_name: dentist-be-redis
    ports:
      - "8081:6379"
    volumes:
      - redis-data:/data
    restart: always
volumes:
  redis-data: